// Inverse kinematics against the real ur5e model.
//
//   npm run test:ik
//
// Offline: ur5e is bundled, so this needs no network. The targets are generated by
// forward kinematics from random joint configurations, which means every one is provably
// reachable — a failure is therefore always the solver's fault and never an impossible
// request. That property is what makes the pass/fail line meaningful.

import fs from 'node:fs';
import path from 'node:path';
import load_mujoco from '../dist/mujoco_wasm.js';
import { mujocoLogHooks } from '../examples/utils/mujocoLog.js';
import { compileModel } from '../examples/mujocoUtils.js';
import { solveIk } from '../examples/utils/ik.js';
import { matToQuat, quatAngle } from '../examples/utils/mjmath.js';

let failures = 0;
const ok = (m) => console.log(`  ok    ${m}`);
const bad = (m) => { failures++; console.log(`  FAIL  ${m}`); };
const check = (cond, m) => (cond ? ok(m) : bad(m));

// solveIk reads window._pythonShouldStop for interruptibility.
globalThis.window = { _pythonShouldStop: false };

const mujoco = await load_mujoco(mujocoLogHooks);
mujoco.FS.mkdir('/working');
mujoco.FS.mount(mujoco.MEMFS, { root: '.' }, '/working');

const src = path.join(import.meta.dirname, '..', 'examples', 'scenes', 'universal_robots_ur5e');
mujoco.FS.mkdir('/working/universal_robots_ur5e');
mujoco.FS.mkdir('/working/universal_robots_ur5e/assets');
for (const f of fs.readdirSync(src)) {
  const abs = path.join(src, f);
  if (!fs.statSync(abs).isDirectory()) {
    mujoco.FS.writeFile(`/working/universal_robots_ur5e/${f}`, new Uint8Array(fs.readFileSync(abs)));
  }
}
for (const f of fs.readdirSync(path.join(src, 'assets'))) {
  mujoco.FS.writeFile(`/working/universal_robots_ur5e/assets/${f}`,
    new Uint8Array(fs.readFileSync(path.join(src, 'assets', f))));
}

const model = compileModel(mujoco, '/working/universal_robots_ur5e/scene.xml');
const state = new mujoco.State(model);
const simulation = new mujoco.Simulation(model, state);
simulation.forward();

const demo = { model, simulation, mujoco };

// ur5e declares one site, attachment_site, at the tool flange.
const SITE = 0;
console.log(`ur5e: nq=${model.nq} nu=${model.nu} nsite=${model.nsite}`);
check(model.nsite > 0, 'the model has a site to aim at');

function sitePose() {
  return {
    pos: [simulation.site_xpos[3 * SITE], simulation.site_xpos[3 * SITE + 1], simulation.site_xpos[3 * SITE + 2]],
    quat: matToQuat(Array.from(simulation.site_xmat.subarray(9 * SITE, 9 * SITE + 9))),
  };
}

/** Pose the arm and read where the site ends up — a guaranteed-reachable target. */
function poseFor(values) {
  for (let j = 0; j < values.length; j++) simulation.qpos[model.jnt_qposadr[j]] = values[j];
  simulation.kinematics();
  return sitePose();
}

const home = Array.from({ length: model.njnt }, (_, j) => simulation.qpos[model.jnt_qposadr[j]]);

console.log('\nthe solver reaches poses it generated itself');
{
  // Deterministic sequence, so a failure is always reproducible.
  let rng = 987654321;
  const rand = () => { rng = (rng * 1103515245 + 12345) & 0x7fffffff; return rng / 0x7fffffff; };

  const N = 60;
  let converged = 0;
  let worstPos = 0;
  let worstRot = 0;
  let totalMs = 0;
  let totalSeeds = 0;

  for (let t = 0; t < N; t++) {
    const truth = Array.from({ length: model.njnt }, (_, j) => {
      const limited = !!model.jnt_limited[j];
      const lo = limited ? model.jnt_range[2 * j] : -Math.PI;
      const hi = limited ? model.jnt_range[2 * j + 1] : Math.PI;
      return lo + rand() * (hi - lo);
    });
    const target = poseFor(truth);
    // Start each solve from the home pose, not from the answer.
    poseFor(home);

    const r = solveIk(demo, { kind: 'site', index: SITE, pos: target.pos, quat: target.quat });
    totalMs += r.ms;
    totalSeeds += r.seedsTried;
    if (r.success) converged++;
    worstPos = Math.max(worstPos, Math.min(r.posErr, 1e3));
    worstRot = Math.max(worstRot, Math.min(r.rotErr, 1e3));
  }

  console.log(`  ${converged}/${N} converged, worst pos ${(worstPos * 1000).toFixed(3)} mm, `
    + `worst rot ${worstRot.toFixed(5)} rad, mean ${(totalMs / N).toFixed(2)} ms, `
    + `mean seeds ${(totalSeeds / N).toFixed(2)}`);
  // Measured 100/100 at restarts=16; allow a little slack for a different machine
  // without letting a real regression through (restarts=1 scored 71/100).
  check(converged >= N * 0.95, `at least 95% converge (${converged}/${N})`);
  check(worstPos < 1e-3, 'worst position error is under 1 mm');
  check(totalMs / N < 25, 'mean solve time is under 25 ms');
}

console.log('\nrestarts are what make it reliable');
{
  // The justification for the default. If this ever inverts, the default is wrong.
  let rng = 24680;
  const rand = () => { rng = (rng * 1103515245 + 12345) & 0x7fffffff; return rng / 0x7fffffff; };
  const targets = [];
  for (let t = 0; t < 30; t++) {
    const truth = Array.from({ length: model.njnt }, (_, j) => {
      const lo = model.jnt_limited[j] ? model.jnt_range[2 * j] : -Math.PI;
      const hi = model.jnt_limited[j] ? model.jnt_range[2 * j + 1] : Math.PI;
      return lo + rand() * (hi - lo);
    });
    targets.push(poseFor(truth));
  }
  const scoreWith = (restarts) => {
    let n = 0;
    for (const target of targets) {
      poseFor(home);
      if (solveIk(demo, { kind: 'site', index: SITE, pos: target.pos, quat: target.quat, restarts }).success) n++;
    }
    return n;
  };
  const one = scoreWith(1);
  const many = scoreWith(16);
  console.log(`  restarts=1: ${one}/30    restarts=16: ${many}/30`);
  // `many >= one` is worthless on its own: it passed while both were 0, which is how a
  // completely broken solver looked healthy on this line. Require real progress first.
  check(one > 0, 'a single seed solves at least some targets');
  check(many >= one, 'more restarts never solve fewer targets');
  check(many >= 29, 'restarts=16 solves nearly everything');
}

console.log('\nposition-only and orientation-only requests');
{
  const target = poseFor([0.4, -0.9, 1.2, -0.4, 0.3, 0.2]);
  poseFor(home);
  const posOnly = solveIk(demo, { kind: 'site', index: SITE, pos: target.pos });
  check(posOnly.success, 'position-only (orientation free) converges');

  poseFor(home);
  const rotOnly = solveIk(demo, { kind: 'site', index: SITE, quat: target.quat });
  check(rotOnly.success, 'orientation-only (position free) converges');
}

console.log('\nthe scene is left untouched');
{
  poseFor(home);
  simulation.forward();
  const before = Array.from(simulation.qpos);
  const beforeVel = Array.from(simulation.qvel);
  const target = poseFor([0.2, -1.0, 1.0, -0.2, 0.1, 0.0]);
  poseFor(home);
  simulation.forward();

  solveIk(demo, { kind: 'site', index: SITE, pos: target.pos, quat: target.quat });
  const worst = Math.max(...Array.from(simulation.qpos).map((v, i) => Math.abs(v - before[i])));
  check(worst < 1e-12, `qpos is restored exactly (worst drift ${worst.toExponential(1)})`);
  const worstVel = Math.max(...Array.from(simulation.qvel).map((v, i) => Math.abs(v - beforeVel[i])));
  check(worstVel < 1e-12, 'qvel is restored exactly');
}

console.log('\nthe solved qpos really does put the site on target');
{
  const target = poseFor([-0.3, -1.1, 0.9, -0.5, 0.4, 0.1]);
  poseFor(home);
  const r = solveIk(demo, { kind: 'site', index: SITE, pos: target.pos, quat: target.quat });
  check(r.success, 'solve converged');
  // Apply the returned vector and measure independently of the solver's own report.
  for (let i = 0; i < r.qpos.length; i++) simulation.qpos[i] = r.qpos[i];
  simulation.kinematics();
  const got = sitePose();
  const dp = Math.hypot(got.pos[0] - target.pos[0], got.pos[1] - target.pos[1], got.pos[2] - target.pos[2]);
  const dr = quatAngle(got.quat, target.quat);
  check(dp < 1e-3, `applying r.qpos lands within 1 mm (${(dp * 1000).toFixed(4)} mm)`);
  check(dr < 1e-2, `and within 0.01 rad (${dr.toExponential(1)})`);
}

console.log('\nbad requests fail clearly');
{
  const throws = (fn, label) => {
    try { fn(); bad(`${label} — did not throw`); } catch (_) { ok(`${label} throws`); }
  };
  throws(() => solveIk(demo, { kind: 'site', index: SITE }), 'neither pos nor quat');
  throws(() => solveIk({ model: null, simulation: null }, { kind: 'site', index: 0, pos: [0, 0, 0] }),
    'no model loaded');

  // Far outside the workspace: must report failure rather than claim success.
  poseFor(home);
  const unreachable = solveIk(demo, { kind: 'site', index: SITE, pos: [50, 50, 50], restarts: 4 });
  check(!unreachable.success, 'an unreachable target reports success=false');
  check(unreachable.posErr > 1, 'and reports a large position error rather than hiding it');
}

console.log(`\n${failures} failure(s)`);
process.exit(failures ? 1 : 0);
