// GENERATED — do not hand-edit.
export const MENAGERIE_MODELS = [
  {
    "id": "franka_fr3_v2/fr3v2",
    "name": "Franka Robotics FR3 v2",
    "maker": "Franka Fr3",
    "maker_folder": "franka_fr3_v2",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "franka_fr3_v2/scene.xml",
    "thumbnail": "/menagerie/franka_fr3_v2/fr3v2.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/franka_fr3_v2/scene.xml"
  },
  {
    "id": "arx_l5/arx_l5",
    "name": "arx_l5",
    "maker": "Arx",
    "maker_folder": "arx_l5",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "arx_l5/scene.xml",
    "thumbnail": "/menagerie/arx_l5/arx_l5.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/arx_l5/scene.xml"
  },
  {
    "id": "dynamixel_2r/dynamixel_2r",
    "name": "dynamixel_2r",
    "maker": "Dynamixel",
    "maker_folder": "dynamixel_2r",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "dynamixel_2r/scene.xml",
    "thumbnail": "/menagerie/dynamixel_2r/dynamixel_2r.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/dynamixel_2r/scene.xml"
  },
  {
    "id": "flexiv_rizon4/flexiv_rizon4",
    "name": "flexiv_rizon4",
    "maker": "Flexiv Rizon4",
    "maker_folder": "flexiv_rizon4",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "flexiv_rizon4/scene.xml",
    "thumbnail": "/menagerie/flexiv_rizon4/flexiv_rizon4.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/flexiv_rizon4/scene.xml"
  },
  {
    "id": "flexiv_rizon4s/flexiv_rizon4s",
    "name": "flexiv_rizon4s",
    "maker": "Flexiv Rizon4s",
    "maker_folder": "flexiv_rizon4s",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "flexiv_rizon4s/scene.xml",
    "thumbnail": "/menagerie/flexiv_rizon4s/flexiv_rizon4s.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/flexiv_rizon4s/scene.xml"
  },
  {
    "id": "franka_fr3/fr3",
    "name": "fr3",
    "maker": "Franka Fr3",
    "maker_folder": "franka_fr3",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "franka_fr3/scene.xml",
    "thumbnail": "/menagerie/franka_fr3/fr3.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/franka_fr3/scene.xml"
  },
  {
    "id": "kinova_gen3/gen3",
    "name": "gen3",
    "maker": "Kinova",
    "maker_folder": "kinova_gen3",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "kinova_gen3/scene.xml",
    "thumbnail": "/menagerie/kinova_gen3/gen3.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/kinova_gen3/scene.xml"
  },
  {
    "id": "kuka_iiwa_14/iiwa14",
    "name": "iiwa14",
    "maker": "Kuka",
    "maker_folder": "kuka_iiwa_14",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "kuka_iiwa_14/scene.xml",
    "thumbnail": null,
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/kuka_iiwa_14/scene.xml"
  },
  {
    "id": "ufactory_lite6/lite6",
    "name": "lite6",
    "maker": "Ufactory",
    "maker_folder": "ufactory_lite6",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "ufactory_lite6/scene.xml",
    "thumbnail": "/menagerie/ufactory_lite6/lite6.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/ufactory_lite6/scene.xml"
  },
  {
    "id": "low_cost_robot_arm/low_cost_robot_arm",
    "name": "low_cost_robot_arm",
    "maker": "Low",
    "maker_folder": "low_cost_robot_arm",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "low_cost_robot_arm/scene.xml",
    "thumbnail": "/menagerie/low_cost_robot_arm/low_cost_robot_arm.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/low_cost_robot_arm/scene.xml"
  },
  {
    "id": "franka_emika_panda/panda",
    "name": "panda",
    "maker": "Franka Emika",
    "maker_folder": "franka_emika_panda",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "franka_emika_panda/scene.xml",
    "thumbnail": "/menagerie/franka_emika_panda/panda.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/franka_emika_panda/scene.xml"
  },
  {
    "id": "agilex_piper/piper",
    "name": "piper",
    "maker": "Agilex",
    "maker_folder": "agilex_piper",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "agilex_piper/scene.xml",
    "thumbnail": "/menagerie/agilex_piper/piper.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/agilex_piper/scene.xml"
  },
  {
    "id": "rethink_robotics_sawyer/sawyer",
    "name": "sawyer",
    "maker": "Rethink Robotics",
    "maker_folder": "rethink_robotics_sawyer",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "rethink_robotics_sawyer/scene.xml",
    "thumbnail": "/menagerie/rethink_robotics_sawyer/sawyer.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/rethink_robotics_sawyer/scene.xml"
  },
  {
    "id": "seeed_rebot_devarm/seeed_rebot_devarm",
    "name": "seeed_rebot_devarm",
    "maker": "Seeed",
    "maker_folder": "seeed_rebot_devarm",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "seeed_rebot_devarm/scene.xml",
    "thumbnail": "/menagerie/seeed_rebot_devarm/seeed_rebot_devarm.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/seeed_rebot_devarm/scene.xml"
  },
  {
    "id": "robotstudio_so101/so101",
    "name": "so101",
    "maker": "Robotstudio",
    "maker_folder": "robotstudio_so101",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "robotstudio_so101/scene.xml",
    "thumbnail": "/menagerie/robotstudio_so101/so101.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/robotstudio_so101/scene.xml"
  },
  {
    "id": "trs_so_arm100/so_arm100",
    "name": "so_arm100",
    "maker": "Trs",
    "maker_folder": "trs_so_arm100",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "trs_so_arm100/scene.xml",
    "thumbnail": "/menagerie/trs_so_arm100/so_arm100.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/trs_so_arm100/scene.xml"
  },
  {
    "id": "universal_robots_ur10e/ur10e",
    "name": "ur10e",
    "maker": "Universal Robots",
    "maker_folder": "universal_robots_ur10e",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "universal_robots_ur10e/scene.xml",
    "thumbnail": "/menagerie/universal_robots_ur10e/ur10e.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/universal_robots_ur10e/scene.xml"
  },
  {
    "id": "universal_robots_ur5e/ur5e",
    "name": "ur5e",
    "maker": "Universal Robots",
    "maker_folder": "universal_robots_ur5e",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "universal_robots_ur5e/scene.xml",
    "thumbnail": "/menagerie/universal_robots_ur5e/ur5e.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/universal_robots_ur5e/scene.xml"
  },
  {
    "id": "trossen_vx300s/vx300s",
    "name": "vx300s",
    "maker": "Trossen",
    "maker_folder": "trossen_vx300s",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "trossen_vx300s/scene.xml",
    "thumbnail": "/menagerie/trossen_vx300s/vx300s.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/trossen_vx300s/scene.xml"
  },
  {
    "id": "trossen_wx250s/wx250s",
    "name": "wx250s",
    "maker": "Trossen",
    "maker_folder": "trossen_wx250s",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "trossen_wx250s/scene.xml",
    "thumbnail": "/menagerie/trossen_wx250s/wx250s.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/trossen_wx250s/scene.xml"
  },
  {
    "id": "trossen_wxai/wxai_follower",
    "name": "wxai_follower",
    "maker": "Trossen",
    "maker_folder": "trossen_wxai",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "trossen_wxai/scene.xml",
    "thumbnail": null,
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/trossen_wxai/scene.xml"
  },
  {
    "id": "ufactory_xarm7/xarm7",
    "name": "xarm7",
    "maker": "Ufactory",
    "maker_folder": "ufactory_xarm7",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "ufactory_xarm7/scene.xml",
    "thumbnail": "/menagerie/ufactory_xarm7/xarm7.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/ufactory_xarm7/scene.xml"
  },
  {
    "id": "i2rt_yam/yam",
    "name": "yam",
    "maker": "I2rt",
    "maker_folder": "i2rt_yam",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "i2rt_yam/scene.xml",
    "thumbnail": "/menagerie/i2rt_yam/yam.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/i2rt_yam/scene.xml"
  },
  {
    "id": "unitree_z1/z1",
    "name": "z1",
    "maker": "Unitree Z1",
    "maker_folder": "unitree_z1",
    "category_id": 0,
    "category_name": "ARM",
    "category_label": "Arm",
    "xml_path": "unitree_z1/scene.xml",
    "thumbnail": "/menagerie/unitree_z1/z1.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/unitree_z1/scene.xml"
  },
  {
    "id": "ms_human_700/MS-Human-700",
    "name": "MS-Human-700",
    "maker": "Ms",
    "maker_folder": "ms_human_700",
    "category_id": 9,
    "category_name": "BIOMECHANICAL",
    "category_label": "Biomechanical",
    "xml_path": "ms_human_700/scene.xml",
    "thumbnail": null,
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/ms_human_700/scene.xml"
  },
  {
    "id": "flybody/fruitfly",
    "name": "fruitfly",
    "maker": "Flybody",
    "maker_folder": "flybody",
    "category_id": 9,
    "category_name": "BIOMECHANICAL",
    "category_label": "Biomechanical",
    "xml_path": "flybody/scene.xml",
    "thumbnail": null,
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/flybody/scene.xml"
  },
  {
    "id": "iit_softfoot/softfoot",
    "name": "softfoot",
    "maker": "Iit",
    "maker_folder": "iit_softfoot",
    "category_id": 9,
    "category_name": "BIOMECHANICAL",
    "category_label": "Biomechanical",
    "xml_path": "iit_softfoot/scene.xml",
    "thumbnail": "/menagerie/iit_softfoot/softfoot.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/iit_softfoot/scene.xml"
  },
  {
    "id": "agility_cassie/cassie",
    "name": "cassie",
    "maker": "Agility",
    "maker_folder": "agility_cassie",
    "category_id": 6,
    "category_name": "BIPED",
    "category_label": "Biped",
    "xml_path": "agility_cassie/scene.xml",
    "thumbnail": "/menagerie/agility_cassie/cassie.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/agility_cassie/scene.xml"
  },
  {
    "id": "bitcraze_crazyflie_2/cf2",
    "name": "cf2",
    "maker": "Bitcraze",
    "maker_folder": "bitcraze_crazyflie_2",
    "category_id": 8,
    "category_name": "DRONE",
    "category_label": "Drone",
    "xml_path": "bitcraze_crazyflie_2/scene.xml",
    "thumbnail": "/menagerie/bitcraze_crazyflie_2/cf2.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/bitcraze_crazyflie_2/scene.xml"
  },
  {
    "id": "skydio_x2/x2",
    "name": "x2",
    "maker": "Skydio",
    "maker_folder": "skydio_x2",
    "category_id": 8,
    "category_name": "DRONE",
    "category_label": "Drone",
    "xml_path": "skydio_x2/scene.xml",
    "thumbnail": "/menagerie/skydio_x2/x2.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/skydio_x2/scene.xml"
  },
  {
    "id": "aloha/aloha",
    "name": "aloha",
    "maker": "Aloha",
    "maker_folder": "aloha",
    "category_id": 1,
    "category_name": "DUAL_ARM",
    "category_label": "Dual Arm",
    "xml_path": "aloha/scene.xml",
    "thumbnail": "/menagerie/aloha/aloha.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/aloha/scene.xml"
  },
  {
    "id": "robotiq_2f85/2f85",
    "name": "2f85",
    "maker": "Robotiq",
    "maker_folder": "robotiq_2f85",
    "category_id": 2,
    "category_name": "END_EFFECTOR",
    "category_label": "Gripper",
    "xml_path": "robotiq_2f85/scene.xml",
    "thumbnail": "/menagerie/robotiq_2f85/2f85.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/robotiq_2f85/scene.xml"
  },
  {
    "id": "franka_emika_panda/hand",
    "name": "Panda Gripper",
    "maker": "Franka Emika",
    "maker_folder": "franka_emika_panda",
    "category_id": 2,
    "category_name": "END_EFFECTOR",
    "category_label": "Gripper",
    "xml_path": "franka_emika_panda/hand.xml",
    "thumbnail": null,
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/franka_emika_panda/hand.xml"
  },
  {
    "id": "robotiq_2f85_v4/2f85",
    "name": "Robotiq 2F-85 v4",
    "maker": "Robotiq",
    "maker_folder": "robotiq_2f85_v4",
    "category_id": 2,
    "category_name": "END_EFFECTOR",
    "category_label": "Gripper",
    "xml_path": "robotiq_2f85_v4/scene.xml",
    "thumbnail": "/menagerie/robotiq_2f85_v4/2f85.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/robotiq_2f85_v4/scene.xml"
  },
  {
    "id": "wonik_allegro/left_hand",
    "name": "left_hand",
    "maker": "Wonik",
    "maker_folder": "wonik_allegro",
    "category_id": 2,
    "category_name": "END_EFFECTOR",
    "category_label": "Gripper",
    "xml_path": "wonik_allegro/scene_left.xml",
    "thumbnail": null,
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/wonik_allegro/scene_left.xml"
  },
  {
    "id": "shadow_hand/left_hand",
    "name": "left_hand",
    "maker": "Shadow",
    "maker_folder": "shadow_hand",
    "category_id": 2,
    "category_name": "END_EFFECTOR",
    "category_label": "Gripper",
    "xml_path": "shadow_hand/scene_left.xml",
    "thumbnail": null,
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/shadow_hand/scene_left.xml"
  },
  {
    "id": "leap_hand/left_hand",
    "name": "left_hand",
    "maker": "Leap",
    "maker_folder": "leap_hand",
    "category_id": 2,
    "category_name": "END_EFFECTOR",
    "category_label": "Gripper",
    "xml_path": "leap_hand/scene_left.xml",
    "thumbnail": null,
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/leap_hand/scene_left.xml"
  },
  {
    "id": "sharpa_wave/left_hand",
    "name": "left_hand",
    "maker": "Sharpa",
    "maker_folder": "sharpa_wave",
    "category_id": 2,
    "category_name": "END_EFFECTOR",
    "category_label": "Gripper",
    "xml_path": "sharpa_wave/scene_left.xml",
    "thumbnail": null,
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/sharpa_wave/scene_left.xml"
  },
  {
    "id": "tetheria_aero_hand_open/right_hand",
    "name": "right_hand",
    "maker": "Tetheria",
    "maker_folder": "tetheria_aero_hand_open",
    "category_id": 2,
    "category_name": "END_EFFECTOR",
    "category_label": "Gripper",
    "xml_path": "tetheria_aero_hand_open/scene_right.xml",
    "thumbnail": null,
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/tetheria_aero_hand_open/scene_right.xml"
  },
  {
    "id": "shadow_dexee/shadow_dexee",
    "name": "shadow_dexee",
    "maker": "Shadow",
    "maker_folder": "shadow_dexee",
    "category_id": 2,
    "category_name": "END_EFFECTOR",
    "category_label": "Gripper",
    "xml_path": "shadow_dexee/scene.xml",
    "thumbnail": "/menagerie/shadow_dexee/shadow_dexee.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/shadow_dexee/scene.xml"
  },
  {
    "id": "umi_gripper/umi_gripper",
    "name": "umi_gripper",
    "maker": "Umi",
    "maker_folder": "umi_gripper",
    "category_id": 2,
    "category_name": "END_EFFECTOR",
    "category_label": "Gripper",
    "xml_path": "umi_gripper/scene.xml",
    "thumbnail": "/menagerie/umi_gripper/umi_gripper.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/umi_gripper/scene.xml"
  },
  {
    "id": "ufactory_xarm7/hand",
    "name": "xarm7 Gripper",
    "maker": "Ufactory",
    "maker_folder": "ufactory_xarm7",
    "category_id": 2,
    "category_name": "END_EFFECTOR",
    "category_label": "Gripper",
    "xml_path": "ufactory_xarm7/hand.xml",
    "thumbnail": null,
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/ufactory_xarm7/hand.xml"
  },
  {
    "id": "pndbotics_adam_lite/adam_lite",
    "name": "adam_lite",
    "maker": "Pndbotics",
    "maker_folder": "pndbotics_adam_lite",
    "category_id": 7,
    "category_name": "HUMANOID",
    "category_label": "Humanoid",
    "xml_path": "pndbotics_adam_lite/scene.xml",
    "thumbnail": "/menagerie/pndbotics_adam_lite/adam_lite.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/pndbotics_adam_lite/scene.xml"
  },
  {
    "id": "apptronik_apollo/apptronik_apollo",
    "name": "apptronik_apollo",
    "maker": "Apptronik Apollo",
    "maker_folder": "apptronik_apollo",
    "category_id": 7,
    "category_name": "HUMANOID",
    "category_label": "Humanoid",
    "xml_path": "apptronik_apollo/scene.xml",
    "thumbnail": "/menagerie/apptronik_apollo/apptronik_apollo.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/apptronik_apollo/scene.xml"
  },
  {
    "id": "berkeley_humanoid/berkeley_humanoid",
    "name": "berkeley_humanoid",
    "maker": "Berkeley",
    "maker_folder": "berkeley_humanoid",
    "category_id": 7,
    "category_name": "HUMANOID",
    "category_label": "Humanoid",
    "xml_path": "berkeley_humanoid/scene.xml",
    "thumbnail": "/menagerie/berkeley_humanoid/berkeley_humanoid.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/berkeley_humanoid/scene.xml"
  },
  {
    "id": "unitree_g1/g1",
    "name": "g1",
    "maker": "Unitree G1",
    "maker_folder": "unitree_g1",
    "category_id": 7,
    "category_name": "HUMANOID",
    "category_label": "Humanoid",
    "xml_path": "unitree_g1/scene.xml",
    "thumbnail": "/menagerie/unitree_g1/g1.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/unitree_g1/scene.xml"
  },
  {
    "id": "unitree_h1/h1",
    "name": "h1",
    "maker": "Unitree H1",
    "maker_folder": "unitree_h1",
    "category_id": 7,
    "category_name": "HUMANOID",
    "category_label": "Humanoid",
    "xml_path": "unitree_h1/scene.xml",
    "thumbnail": "/menagerie/unitree_h1/h1.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/unitree_h1/scene.xml"
  },
  {
    "id": "fourier_n1/n1",
    "name": "n1",
    "maker": "Fourier",
    "maker_folder": "fourier_n1",
    "category_id": 7,
    "category_name": "HUMANOID",
    "category_label": "Humanoid",
    "xml_path": "fourier_n1/scene.xml",
    "thumbnail": "/menagerie/fourier_n1/n1.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/fourier_n1/scene.xml"
  },
  {
    "id": "robotis_op3/op3",
    "name": "op3",
    "maker": "Robotis",
    "maker_folder": "robotis_op3",
    "category_id": 7,
    "category_name": "HUMANOID",
    "category_label": "Humanoid",
    "xml_path": "robotis_op3/scene.xml",
    "thumbnail": "/menagerie/robotis_op3/op3.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/robotis_op3/scene.xml"
  },
  {
    "id": "booster_t1/t1",
    "name": "t1",
    "maker": "Booster",
    "maker_folder": "booster_t1",
    "category_id": 7,
    "category_name": "HUMANOID",
    "category_label": "Humanoid",
    "xml_path": "booster_t1/scene.xml",
    "thumbnail": "/menagerie/booster_t1/t1.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/booster_t1/scene.xml"
  },
  {
    "id": "pal_talos/talos",
    "name": "talos",
    "maker": "Pal Talos",
    "maker_folder": "pal_talos",
    "category_id": 7,
    "category_name": "HUMANOID",
    "category_label": "Humanoid",
    "xml_path": "pal_talos/scene_position.xml",
    "thumbnail": "/menagerie/pal_talos/talos.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/pal_talos/scene_position.xml"
  },
  {
    "id": "toddlerbot_2xc/toddlerbot_2xc",
    "name": "toddlerbot_2xc",
    "maker": "Toddlerbot",
    "maker_folder": "toddlerbot_2xc",
    "category_id": 7,
    "category_name": "HUMANOID",
    "category_label": "Humanoid",
    "xml_path": "toddlerbot_2xc/scene.xml",
    "thumbnail": "/menagerie/toddlerbot_2xc/toddlerbot_2xc.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/toddlerbot_2xc/scene.xml"
  },
  {
    "id": "toddlerbot_2xm/toddlerbot_2xm",
    "name": "toddlerbot_2xm",
    "maker": "Toddlerbot",
    "maker_folder": "toddlerbot_2xm",
    "category_id": 7,
    "category_name": "HUMANOID",
    "category_label": "Humanoid",
    "xml_path": "toddlerbot_2xm/scene.xml",
    "thumbnail": "/menagerie/toddlerbot_2xm/toddlerbot_2xm.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/toddlerbot_2xm/scene.xml"
  },
  {
    "id": "realsense_d435i/d435i",
    "name": "d435i",
    "maker": "Realsense",
    "maker_folder": "realsense_d435i",
    "category_id": 10,
    "category_name": "MISC",
    "category_label": "Misc",
    "xml_path": "realsense_d435i/d435i.xml",
    "thumbnail": "/menagerie/realsense_d435i/d435i.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/realsense_d435i/d435i.xml"
  },
  {
    "id": "robot_soccer_kit/robot_soccer_kit",
    "name": "robot_soccer_kit",
    "maker": "Robot",
    "maker_folder": "robot_soccer_kit",
    "category_id": 4,
    "category_name": "MOBILE_BASE",
    "category_label": "Mobile Base",
    "xml_path": "robot_soccer_kit/scene.xml",
    "thumbnail": "/menagerie/robot_soccer_kit/robot_soccer_kit.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/robot_soccer_kit/scene.xml"
  },
  {
    "id": "rainbow_robotics_rby1/rby1a_1.2",
    "name": "rby1a_1.2",
    "maker": "Rainbow",
    "maker_folder": "rainbow_robotics_rby1",
    "category_id": 3,
    "category_name": "MOBILE_MANIPULATOR",
    "category_label": "Mobile Manipulator",
    "xml_path": "rainbow_robotics_rby1/scene_rby1a_1.2.xml",
    "thumbnail": null,
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/rainbow_robotics_rby1/scene_rby1a_1.2.xml"
  },
  {
    "id": "google_robot/robot",
    "name": "robot",
    "maker": "Google Robot",
    "maker_folder": "google_robot",
    "category_id": 3,
    "category_name": "MOBILE_MANIPULATOR",
    "category_label": "Mobile Manipulator",
    "xml_path": "google_robot/scene.xml",
    "thumbnail": "/menagerie/google_robot/robot.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/google_robot/scene.xml"
  },
  {
    "id": "hello_robot_stretch/stretch",
    "name": "stretch",
    "maker": "Hello Robot",
    "maker_folder": "hello_robot_stretch",
    "category_id": 3,
    "category_name": "MOBILE_MANIPULATOR",
    "category_label": "Mobile Manipulator",
    "xml_path": "hello_robot_stretch/scene.xml",
    "thumbnail": "/menagerie/hello_robot_stretch/stretch.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/hello_robot_stretch/scene.xml"
  },
  {
    "id": "hello_robot_stretch_3/stretch",
    "name": "stretch",
    "maker": "Hello Robot",
    "maker_folder": "hello_robot_stretch_3",
    "category_id": 3,
    "category_name": "MOBILE_MANIPULATOR",
    "category_label": "Mobile Manipulator",
    "xml_path": "hello_robot_stretch_3/scene.xml",
    "thumbnail": "/menagerie/hello_robot_stretch_3/stretch.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/hello_robot_stretch_3/scene.xml"
  },
  {
    "id": "pal_tiago/tiago",
    "name": "tiago",
    "maker": "Pal Tiago",
    "maker_folder": "pal_tiago",
    "category_id": 3,
    "category_name": "MOBILE_MANIPULATOR",
    "category_label": "Mobile Manipulator",
    "xml_path": "pal_tiago/scene_position.xml",
    "thumbnail": "/menagerie/pal_tiago/tiago.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/pal_tiago/scene_position.xml"
  },
  {
    "id": "pal_tiago_dual/tiago_dual",
    "name": "tiago_dual",
    "maker": "Pal Tiago",
    "maker_folder": "pal_tiago_dual",
    "category_id": 3,
    "category_name": "MOBILE_MANIPULATOR",
    "category_label": "Mobile Manipulator",
    "xml_path": "pal_tiago_dual/scene_position.xml",
    "thumbnail": "/menagerie/pal_tiago_dual/tiago_dual.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/pal_tiago_dual/scene_position.xml"
  },
  {
    "id": "stanford_tidybot/tidybot",
    "name": "tidybot",
    "maker": "Stanford",
    "maker_folder": "stanford_tidybot",
    "category_id": 3,
    "category_name": "MOBILE_MANIPULATOR",
    "category_label": "Mobile Manipulator",
    "xml_path": "stanford_tidybot/scene.xml",
    "thumbnail": "/menagerie/stanford_tidybot/tidybot.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/stanford_tidybot/scene.xml"
  },
  {
    "id": "unitree_a1/a1",
    "name": "a1",
    "maker": "Unitree A1",
    "maker_folder": "unitree_a1",
    "category_id": 5,
    "category_name": "QUADRUPED",
    "category_label": "Quadruped",
    "xml_path": "unitree_a1/scene.xml",
    "thumbnail": "/menagerie/unitree_a1/a1.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/unitree_a1/scene.xml"
  },
  {
    "id": "anybotics_anymal_b/anymal_b",
    "name": "anymal_b",
    "maker": "Anybotics Anymal",
    "maker_folder": "anybotics_anymal_b",
    "category_id": 5,
    "category_name": "QUADRUPED",
    "category_label": "Quadruped",
    "xml_path": "anybotics_anymal_b/scene.xml",
    "thumbnail": "/menagerie/anybotics_anymal_b/anymal_b.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/anybotics_anymal_b/scene.xml"
  },
  {
    "id": "anybotics_anymal_c/anymal_c",
    "name": "anymal_c",
    "maker": "Anybotics Anymal",
    "maker_folder": "anybotics_anymal_c",
    "category_id": 5,
    "category_name": "QUADRUPED",
    "category_label": "Quadruped",
    "xml_path": "anybotics_anymal_c/scene.xml",
    "thumbnail": "/menagerie/anybotics_anymal_c/anymal_c.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/anybotics_anymal_c/scene.xml"
  },
  {
    "id": "google_barkour_v0/barkour_v0",
    "name": "barkour_v0",
    "maker": "Google Barkour",
    "maker_folder": "google_barkour_v0",
    "category_id": 5,
    "category_name": "QUADRUPED",
    "category_label": "Quadruped",
    "xml_path": "google_barkour_v0/scene.xml",
    "thumbnail": "/menagerie/google_barkour_v0/barkour_v0.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/google_barkour_v0/scene.xml"
  },
  {
    "id": "google_barkour_vb/barkour_vb",
    "name": "barkour_vb",
    "maker": "Google Barkour",
    "maker_folder": "google_barkour_vb",
    "category_id": 5,
    "category_name": "QUADRUPED",
    "category_label": "Quadruped",
    "xml_path": "google_barkour_vb/scene.xml",
    "thumbnail": "/menagerie/google_barkour_vb/barkour_vb.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/google_barkour_vb/scene.xml"
  },
  {
    "id": "unitree_go1/go1",
    "name": "go1",
    "maker": "Unitree Go1",
    "maker_folder": "unitree_go1",
    "category_id": 5,
    "category_name": "QUADRUPED",
    "category_label": "Quadruped",
    "xml_path": "unitree_go1/scene.xml",
    "thumbnail": "/menagerie/unitree_go1/go1.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/unitree_go1/scene.xml"
  },
  {
    "id": "unitree_go2/go2",
    "name": "go2",
    "maker": "Unitree Go2",
    "maker_folder": "unitree_go2",
    "category_id": 5,
    "category_name": "QUADRUPED",
    "category_label": "Quadruped",
    "xml_path": "unitree_go2/scene.xml",
    "thumbnail": "/menagerie/unitree_go2/go2.png",
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/unitree_go2/scene.xml"
  },
  {
    "id": "boston_dynamics_spot/spot_arm",
    "name": "spot_arm",
    "maker": "Boston Dynamics",
    "maker_folder": "boston_dynamics_spot",
    "category_id": 5,
    "category_name": "QUADRUPED",
    "category_label": "Quadruped",
    "xml_path": "boston_dynamics_spot/scene.xml",
    "thumbnail": null,
    "github_raw_url": "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/main/boston_dynamics_spot/scene.xml"
  }
];
